FROM ghcr.io/iamkalefreeman/comfyui-api:comfy0.3.60-torch2.8.0-cuda12.8-runtime

COPY test/docker-image/dreamshaper_8.safetensors $MODEL_DIR/checkpoints/dreamshaper_8.safetensors

COPY bin/comfyui-api /comfyui-api
RUN chmod +x /comfyui-api

ENV LOG_LEVEL=debug

CMD ["/comfyui-api"]
